---
- hosts: localhost
  connection: local

  tasks:
    - name: Create EC2 instances
      amazon.aws.ec2_instance:
        name: "{{item.name}}"
        key_name: "7.20"
        instance_type: t2.micro
        security_group: default
        region: us-east-1
        aws_access_key: "{{ec2_access_key}}"
        aws_secret_key: "{{ec2_secret_key}}"
        network:
          assign_public_ip: true
        image_id: "{{item.image}}"
        tags:
          environment: "{{item.name}}"
      loop:
        - { image: "ami-0e1d06225679bc1c5", name: "manage-node-1" }
        - { image: "ami-0f58b397bc5c1f2e8", name: "manage-node-2" }
        - { image: "ami-0f58b397bc5c1f2e8", name: "manage-node-3" }
